/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.validation;

import org.xtext.example.bot.validation.AbstractMyBotValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyBotValidator extends AbstractMyBotValidator {
}
