/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.bot.ui.AbstractMyBotUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyBotUiModule extends AbstractMyBotUiModule {
  public MyBotUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
