/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.ui.contentassist;

import org.xtext.example.bot.ui.contentassist.AbstractMyBotProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyBotProposalProvider extends AbstractMyBotProposalProvider {
}
