/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot;

import org.xtext.example.bot.MyBotStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyBotStandaloneSetup extends MyBotStandaloneSetupGenerated {
  public static void doSetup() {
    new MyBotStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
