/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot;

import org.xtext.example.bot.AbstractMyBotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyBotRuntimeModule extends AbstractMyBotRuntimeModule {
}
