/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyBotRuntimeModule extends AbstractMyBotRuntimeModule {
}
