/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.bot.MyBotRuntimeModule;
import org.xtext.example.bot.MyBotStandaloneSetup;
import org.xtext.example.bot.ide.MyBotIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyBotIdeSetup extends MyBotStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyBotRuntimeModule _myBotRuntimeModule = new MyBotRuntimeModule();
    MyBotIdeModule _myBotIdeModule = new MyBotIdeModule();
    return Guice.createInjector(Modules2.mixin(_myBotRuntimeModule, _myBotIdeModule));
  }
}
