/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.ide;

import org.xtext.example.bot.ide.AbstractMyBotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyBotIdeModule extends AbstractMyBotIdeModule {
}
