/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyBotScopeProvider extends DelegatingScopeProvider {
}
