/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.myBot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Recommend</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bot.myBot.ActionRecommend#getText <em>Text</em>}</li>
 *   <li>{@link org.xtext.example.bot.myBot.ActionRecommend#getAskRecommend <em>Ask Recommend</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bot.myBot.MyBotPackage#getActionRecommend()
 * @model
 * @generated
 */
public interface ActionRecommend extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bot.myBot.Text}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference list.
   * @see org.xtext.example.bot.myBot.MyBotPackage#getActionRecommend_Text()
   * @model containment="true"
   * @generated
   */
  EList<Text> getText();

  /**
   * Returns the value of the '<em><b>Ask Recommend</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bot.myBot.AskRecommend}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ask Recommend</em>' containment reference list.
   * @see org.xtext.example.bot.myBot.MyBotPackage#getActionRecommend_AskRecommend()
   * @model containment="true"
   * @generated
   */
  EList<AskRecommend> getAskRecommend();

} // ActionRecommend
