/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.myBot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bot.myBot.Bot#getShows <em>Shows</em>}</li>
 *   <li>{@link org.xtext.example.bot.myBot.Bot#getState <em>State</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bot.myBot.MyBotPackage#getBot()
 * @model
 * @generated
 */
public interface Bot extends EObject
{
  /**
   * Returns the value of the '<em><b>Shows</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bot.myBot.Shows}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shows</em>' containment reference list.
   * @see org.xtext.example.bot.myBot.MyBotPackage#getBot_Shows()
   * @model containment="true"
   * @generated
   */
  EList<Shows> getShows();

  /**
   * Returns the value of the '<em><b>State</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bot.myBot.State}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' containment reference list.
   * @see org.xtext.example.bot.myBot.MyBotPackage#getBot_State()
   * @model containment="true"
   * @generated
   */
  EList<State> getState();

} // Bot
