/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.myBot;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.bot.myBot.MyBotFactory
 * @model kind="package"
 * @generated
 */
public interface MyBotPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myBot";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/bot/MyBot";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myBot";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyBotPackage eINSTANCE = org.xtext.example.bot.myBot.impl.MyBotPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.BotImpl <em>Bot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.BotImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getBot()
   * @generated
   */
  int BOT = 0;

  /**
   * The feature id for the '<em><b>Shows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOT__SHOWS = 0;

  /**
   * The feature id for the '<em><b>State</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOT__STATE = 1;

  /**
   * The number of structural features of the '<em>Bot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.ShowsImpl <em>Shows</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.ShowsImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getShows()
   * @generated
   */
  int SHOWS = 1;

  /**
   * The feature id for the '<em><b>Show Type</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOWS__SHOW_TYPE = 0;

  /**
   * The feature id for the '<em><b>Genre</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOWS__GENRE = 1;

  /**
   * The feature id for the '<em><b>Language</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOWS__LANGUAGE = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOWS__TITLE = 3;

  /**
   * The number of structural features of the '<em>Shows</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOWS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.ShowTypeImpl <em>Show Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.ShowTypeImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getShowType()
   * @generated
   */
  int SHOW_TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOW_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Show Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHOW_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.GenreImpl <em>Genre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.GenreImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getGenre()
   * @generated
   */
  int GENRE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENRE__NAME = 0;

  /**
   * The number of structural features of the '<em>Genre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENRE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.LanguageImpl <em>Language</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.LanguageImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getLanguage()
   * @generated
   */
  int LANGUAGE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE__NAME = 0;

  /**
   * The number of structural features of the '<em>Language</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.TitleImpl <em>Title</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.TitleImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getTitle()
   * @generated
   */
  int TITLE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Title</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.StateImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getState()
   * @generated
   */
  int STATE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Action Say</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__ACTION_SAY = 1;

  /**
   * The feature id for the '<em><b>Action Ask</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__ACTION_ASK = 2;

  /**
   * The feature id for the '<em><b>Action Recommend</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__ACTION_RECOMMEND = 3;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.ActionSayImpl <em>Action Say</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.ActionSayImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getActionSay()
   * @generated
   */
  int ACTION_SAY = 7;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_SAY__TEXT = 0;

  /**
   * The number of structural features of the '<em>Action Say</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_SAY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.ActionAskImpl <em>Action Ask</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.ActionAskImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getActionAsk()
   * @generated
   */
  int ACTION_ASK = 8;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_ASK__TEXT = 0;

  /**
   * The feature id for the '<em><b>Ask Variable</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_ASK__ASK_VARIABLE = 1;

  /**
   * The number of structural features of the '<em>Action Ask</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_ASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.ActionRecommendImpl <em>Action Recommend</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.ActionRecommendImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getActionRecommend()
   * @generated
   */
  int ACTION_RECOMMEND = 9;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_RECOMMEND__TEXT = 0;

  /**
   * The feature id for the '<em><b>Ask Recommend</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_RECOMMEND__ASK_RECOMMEND = 1;

  /**
   * The number of structural features of the '<em>Action Recommend</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_RECOMMEND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.TextImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getText()
   * @generated
   */
  int TEXT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__NAME = 0;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.AskVariableImpl <em>Ask Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.AskVariableImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getAskVariable()
   * @generated
   */
  int ASK_VARIABLE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASK_VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Ask Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASK_VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bot.myBot.impl.AskRecommendImpl <em>Ask Recommend</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bot.myBot.impl.AskRecommendImpl
   * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getAskRecommend()
   * @generated
   */
  int ASK_RECOMMEND = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASK_RECOMMEND__NAME = 0;

  /**
   * The number of structural features of the '<em>Ask Recommend</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASK_RECOMMEND_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.Bot <em>Bot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bot</em>'.
   * @see org.xtext.example.bot.myBot.Bot
   * @generated
   */
  EClass getBot();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.Bot#getShows <em>Shows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Shows</em>'.
   * @see org.xtext.example.bot.myBot.Bot#getShows()
   * @see #getBot()
   * @generated
   */
  EReference getBot_Shows();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.Bot#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>State</em>'.
   * @see org.xtext.example.bot.myBot.Bot#getState()
   * @see #getBot()
   * @generated
   */
  EReference getBot_State();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.Shows <em>Shows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shows</em>'.
   * @see org.xtext.example.bot.myBot.Shows
   * @generated
   */
  EClass getShows();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.Shows#getShowType <em>Show Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Show Type</em>'.
   * @see org.xtext.example.bot.myBot.Shows#getShowType()
   * @see #getShows()
   * @generated
   */
  EReference getShows_ShowType();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.Shows#getGenre <em>Genre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Genre</em>'.
   * @see org.xtext.example.bot.myBot.Shows#getGenre()
   * @see #getShows()
   * @generated
   */
  EReference getShows_Genre();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.Shows#getLanguage <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Language</em>'.
   * @see org.xtext.example.bot.myBot.Shows#getLanguage()
   * @see #getShows()
   * @generated
   */
  EReference getShows_Language();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.Shows#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Title</em>'.
   * @see org.xtext.example.bot.myBot.Shows#getTitle()
   * @see #getShows()
   * @generated
   */
  EReference getShows_Title();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.ShowType <em>Show Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Show Type</em>'.
   * @see org.xtext.example.bot.myBot.ShowType
   * @generated
   */
  EClass getShowType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bot.myBot.ShowType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bot.myBot.ShowType#getName()
   * @see #getShowType()
   * @generated
   */
  EAttribute getShowType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.Genre <em>Genre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Genre</em>'.
   * @see org.xtext.example.bot.myBot.Genre
   * @generated
   */
  EClass getGenre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bot.myBot.Genre#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bot.myBot.Genre#getName()
   * @see #getGenre()
   * @generated
   */
  EAttribute getGenre_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.Language <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Language</em>'.
   * @see org.xtext.example.bot.myBot.Language
   * @generated
   */
  EClass getLanguage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bot.myBot.Language#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bot.myBot.Language#getName()
   * @see #getLanguage()
   * @generated
   */
  EAttribute getLanguage_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.Title <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title</em>'.
   * @see org.xtext.example.bot.myBot.Title
   * @generated
   */
  EClass getTitle();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.bot.myBot.Title#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.example.bot.myBot.Title#getName()
   * @see #getTitle()
   * @generated
   */
  EReference getTitle_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see org.xtext.example.bot.myBot.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bot.myBot.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bot.myBot.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.State#getActionSay <em>Action Say</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action Say</em>'.
   * @see org.xtext.example.bot.myBot.State#getActionSay()
   * @see #getState()
   * @generated
   */
  EReference getState_ActionSay();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.State#getActionAsk <em>Action Ask</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action Ask</em>'.
   * @see org.xtext.example.bot.myBot.State#getActionAsk()
   * @see #getState()
   * @generated
   */
  EReference getState_ActionAsk();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.State#getActionRecommend <em>Action Recommend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action Recommend</em>'.
   * @see org.xtext.example.bot.myBot.State#getActionRecommend()
   * @see #getState()
   * @generated
   */
  EReference getState_ActionRecommend();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.ActionSay <em>Action Say</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Say</em>'.
   * @see org.xtext.example.bot.myBot.ActionSay
   * @generated
   */
  EClass getActionSay();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.ActionSay#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Text</em>'.
   * @see org.xtext.example.bot.myBot.ActionSay#getText()
   * @see #getActionSay()
   * @generated
   */
  EReference getActionSay_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.ActionAsk <em>Action Ask</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Ask</em>'.
   * @see org.xtext.example.bot.myBot.ActionAsk
   * @generated
   */
  EClass getActionAsk();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.ActionAsk#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Text</em>'.
   * @see org.xtext.example.bot.myBot.ActionAsk#getText()
   * @see #getActionAsk()
   * @generated
   */
  EReference getActionAsk_Text();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.ActionAsk#getAskVariable <em>Ask Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ask Variable</em>'.
   * @see org.xtext.example.bot.myBot.ActionAsk#getAskVariable()
   * @see #getActionAsk()
   * @generated
   */
  EReference getActionAsk_AskVariable();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.ActionRecommend <em>Action Recommend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Recommend</em>'.
   * @see org.xtext.example.bot.myBot.ActionRecommend
   * @generated
   */
  EClass getActionRecommend();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.ActionRecommend#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Text</em>'.
   * @see org.xtext.example.bot.myBot.ActionRecommend#getText()
   * @see #getActionRecommend()
   * @generated
   */
  EReference getActionRecommend_Text();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bot.myBot.ActionRecommend#getAskRecommend <em>Ask Recommend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ask Recommend</em>'.
   * @see org.xtext.example.bot.myBot.ActionRecommend#getAskRecommend()
   * @see #getActionRecommend()
   * @generated
   */
  EReference getActionRecommend_AskRecommend();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.xtext.example.bot.myBot.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bot.myBot.Text#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bot.myBot.Text#getName()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.AskVariable <em>Ask Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ask Variable</em>'.
   * @see org.xtext.example.bot.myBot.AskVariable
   * @generated
   */
  EClass getAskVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bot.myBot.AskVariable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bot.myBot.AskVariable#getName()
   * @see #getAskVariable()
   * @generated
   */
  EAttribute getAskVariable_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bot.myBot.AskRecommend <em>Ask Recommend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ask Recommend</em>'.
   * @see org.xtext.example.bot.myBot.AskRecommend
   * @generated
   */
  EClass getAskRecommend();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bot.myBot.AskRecommend#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bot.myBot.AskRecommend#getName()
   * @see #getAskRecommend()
   * @generated
   */
  EAttribute getAskRecommend_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyBotFactory getMyBotFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.BotImpl <em>Bot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.BotImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getBot()
     * @generated
     */
    EClass BOT = eINSTANCE.getBot();

    /**
     * The meta object literal for the '<em><b>Shows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOT__SHOWS = eINSTANCE.getBot_Shows();

    /**
     * The meta object literal for the '<em><b>State</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOT__STATE = eINSTANCE.getBot_State();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.ShowsImpl <em>Shows</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.ShowsImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getShows()
     * @generated
     */
    EClass SHOWS = eINSTANCE.getShows();

    /**
     * The meta object literal for the '<em><b>Show Type</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHOWS__SHOW_TYPE = eINSTANCE.getShows_ShowType();

    /**
     * The meta object literal for the '<em><b>Genre</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHOWS__GENRE = eINSTANCE.getShows_Genre();

    /**
     * The meta object literal for the '<em><b>Language</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHOWS__LANGUAGE = eINSTANCE.getShows_Language();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHOWS__TITLE = eINSTANCE.getShows_Title();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.ShowTypeImpl <em>Show Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.ShowTypeImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getShowType()
     * @generated
     */
    EClass SHOW_TYPE = eINSTANCE.getShowType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHOW_TYPE__NAME = eINSTANCE.getShowType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.GenreImpl <em>Genre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.GenreImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getGenre()
     * @generated
     */
    EClass GENRE = eINSTANCE.getGenre();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENRE__NAME = eINSTANCE.getGenre_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.LanguageImpl <em>Language</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.LanguageImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getLanguage()
     * @generated
     */
    EClass LANGUAGE = eINSTANCE.getLanguage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE__NAME = eINSTANCE.getLanguage_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.TitleImpl <em>Title</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.TitleImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getTitle()
     * @generated
     */
    EClass TITLE = eINSTANCE.getTitle();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TITLE__NAME = eINSTANCE.getTitle_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.StateImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Action Say</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__ACTION_SAY = eINSTANCE.getState_ActionSay();

    /**
     * The meta object literal for the '<em><b>Action Ask</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__ACTION_ASK = eINSTANCE.getState_ActionAsk();

    /**
     * The meta object literal for the '<em><b>Action Recommend</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__ACTION_RECOMMEND = eINSTANCE.getState_ActionRecommend();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.ActionSayImpl <em>Action Say</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.ActionSayImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getActionSay()
     * @generated
     */
    EClass ACTION_SAY = eINSTANCE.getActionSay();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_SAY__TEXT = eINSTANCE.getActionSay_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.ActionAskImpl <em>Action Ask</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.ActionAskImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getActionAsk()
     * @generated
     */
    EClass ACTION_ASK = eINSTANCE.getActionAsk();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_ASK__TEXT = eINSTANCE.getActionAsk_Text();

    /**
     * The meta object literal for the '<em><b>Ask Variable</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_ASK__ASK_VARIABLE = eINSTANCE.getActionAsk_AskVariable();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.ActionRecommendImpl <em>Action Recommend</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.ActionRecommendImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getActionRecommend()
     * @generated
     */
    EClass ACTION_RECOMMEND = eINSTANCE.getActionRecommend();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_RECOMMEND__TEXT = eINSTANCE.getActionRecommend_Text();

    /**
     * The meta object literal for the '<em><b>Ask Recommend</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_RECOMMEND__ASK_RECOMMEND = eINSTANCE.getActionRecommend_AskRecommend();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.TextImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__NAME = eINSTANCE.getText_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.AskVariableImpl <em>Ask Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.AskVariableImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getAskVariable()
     * @generated
     */
    EClass ASK_VARIABLE = eINSTANCE.getAskVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASK_VARIABLE__NAME = eINSTANCE.getAskVariable_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.bot.myBot.impl.AskRecommendImpl <em>Ask Recommend</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bot.myBot.impl.AskRecommendImpl
     * @see org.xtext.example.bot.myBot.impl.MyBotPackageImpl#getAskRecommend()
     * @generated
     */
    EClass ASK_RECOMMEND = eINSTANCE.getAskRecommend();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASK_RECOMMEND__NAME = eINSTANCE.getAskRecommend_Name();

  }

} //MyBotPackage
