/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.bot.myBot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bot.myBot.State#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.bot.myBot.State#getActionSay <em>Action Say</em>}</li>
 *   <li>{@link org.xtext.example.bot.myBot.State#getActionAsk <em>Action Ask</em>}</li>
 *   <li>{@link org.xtext.example.bot.myBot.State#getActionRecommend <em>Action Recommend</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bot.myBot.MyBotPackage#getState()
 * @model
 * @generated
 */
public interface State extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.bot.myBot.MyBotPackage#getState_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.bot.myBot.State#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Action Say</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bot.myBot.ActionSay}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Say</em>' containment reference list.
   * @see org.xtext.example.bot.myBot.MyBotPackage#getState_ActionSay()
   * @model containment="true"
   * @generated
   */
  EList<ActionSay> getActionSay();

  /**
   * Returns the value of the '<em><b>Action Ask</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bot.myBot.ActionAsk}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Ask</em>' containment reference list.
   * @see org.xtext.example.bot.myBot.MyBotPackage#getState_ActionAsk()
   * @model containment="true"
   * @generated
   */
  EList<ActionAsk> getActionAsk();

  /**
   * Returns the value of the '<em><b>Action Recommend</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bot.myBot.ActionRecommend}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Recommend</em>' containment reference list.
   * @see org.xtext.example.bot.myBot.MyBotPackage#getState_ActionRecommend()
   * @model containment="true"
   * @generated
   */
  EList<ActionRecommend> getActionRecommend();

} // State
